import TableInSuffIcon from "../../assets/images/ComparePlans/TableinsuffIcon";
import TableinsuffIcon from "../../assets/images/ComparePlans/TableinsuffIcon";
import CheckTickIcon from "../../assets/images/ComparePlans/ChecktickroundImage";

export const TableCardPropsDataForFirst = [
  {
    rowStartHeadValue: "Seats",
    icon: <TableinsuffIcon />,
    content1: "1 Seat",
    content2: "1 Seat",
    content3: "1 Seat",
    content4: "1 Seat",
    content5: "Custom",
  },
  {
    rowStartHeadValue: "Video creation and uploading",
    icon: <TableinsuffIcon />,
    content1: "2 videos / month",
    content2: "60 videos / seat / year",
    content3: "120 videos / seat / year",
    content4: "240 videos / seat / year",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Videos stored in account",
    icon: <TableinsuffIcon />,
    content1: "25 videos",
    content2: "Unlimited",
    content3: "Unlimited",
    content4: "Unlimited",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Virtual Events",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: " - ",
    content3: " - ",
    content4: "Unlimited",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Screen recording",
    icon: <TableinsuffIcon />,
    content1: "25 videos",
    content2: "Unlimited",
    content3: "Unlimited",
    content4: "Unlimited",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Bandwidth",
    icon: <TableinsuffIcon />,
    content1: "2TB bandwidth/month",
    content2: "2TB bandwidth/month",
    content3: "2TB bandwidth/month",
    content4: "2TB bandwidth/month",
    content5: "Custom",
  },
  {
    rowStartHeadValue: "Interactive video",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: "-",
    content4: "-",
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Webinar API",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: "-",
    content4: "-",
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Version history",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: <CheckTickIcon />,
    content4: <CheckTickIcon />,
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Video library",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: <CheckTickIcon />,
    content4: <CheckTickIcon />,
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Training",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: "-",
    content4: "-",
    content5: <CheckTickIcon />,
  },
];

export const TableCardPropsDataForSecondBtn = [
  {
    rowStartHeadValue: "Seats",
    icon: <TableinsuffIcon />,
    content1: "2 Seat",
    content2: "1 Seat",
    content3: "2 Seat",
    content4: "1 Seat",
    content5: "Seat",
  },
  {
    rowStartHeadValue: "Video creation and uploading",
    icon: <TableinsuffIcon />,
    content1: "2 videos / month",
    content2: "600 videos / seat / year",
    content3: "1200 videos / seat / year",
    content4: "2400 videos / seat / year",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Videos stored in account",
    icon: <TableinsuffIcon />,
    content1: "25 videos",
    content2: "50 videos",
    content3: "85 videos",
    content4: "Unlimited",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Virtual Events",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: " - ",
    content3: " - ",
    content4: "Unlimited",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Screen recording",
    icon: <TableinsuffIcon />,
    content1: "25 videos",
    content2: "Unlimited",
    content3: "Unlimited",
    content4: "Unlimited",
    content5: "100 videos",
  },
  {
    rowStartHeadValue: "Bandwidth",
    icon: <TableinsuffIcon />,
    content1: "2TB bandwidth/month",
    content2: "3TB bandwidth/month",
    content3: "4TB bandwidth/month",
    content4: "5TB bandwidth/month",
    content5: "Custom",
  },
  {
    rowStartHeadValue: "Interactive video",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "5TB bandwidth/month",
    content3: "-",
    content4: "5TB bandwidth/month",
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Webinar API",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: "-",
    content4: "-",
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Version history",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: <CheckTickIcon />,
    content4: <CheckTickIcon />,
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Video library",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: <CheckTickIcon />,
    content4: <CheckTickIcon />,
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Training",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: "5TB bandwidth/month",
    content4: "-",
    content5: <CheckTickIcon />,
  },
];

export const TableCardPropsDataForThirdBtn = [
  {
    rowStartHeadValue: "Seats",
    icon: <TableinsuffIcon />,
    content1: "3 Seat",
    content2: "1 Seat",
    content3: "3 Seat",
    content4: "1 Seat",
    content5: "Seat",
  },
  {
    rowStartHeadValue: "Video creation and uploading",
    icon: <TableinsuffIcon />,
    content1: "2 videos / month",
    content2: "500 videos / seat / year",
    content3: "1000 videos / seat / year",
    content4: "2500 videos / seat / year",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Videos stored in account",
    icon: <TableinsuffIcon />,
    content1: "25 videos",
    content2: "85 videos",
    content3: "100 videos",
    content4: "Unlimited",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Virtual Events",
    icon: <TableinsuffIcon />,
    content1: " Unlimited ",
    content2: " - ",
    content3: " - ",
    content4: " -",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Screen recording",
    icon: <TableinsuffIcon />,
    content1: "25 videos",
    content2: "Unlimited",
    content3: "Unlimited",
    content4: "Unlimited",
    content5: "120 videos",
  },
  {
    rowStartHeadValue: "Bandwidth",
    icon: <TableinsuffIcon />,
    content1: "2TB bandwidth/month",
    content2: "7TB bandwidth/month",
    content3: "4TB bandwidth/month",
    content4: "5TB bandwidth/month",
    content5: "Custom",
  },
  {
    rowStartHeadValue: "Interactive video",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "6TB bandwidth/month",
    content3: "-",
    content4: "6TB bandwidth/month",
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Webinar API",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: "Unlimited",
    content4: "-",
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Version history",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: <CheckTickIcon />,
    content4: <CheckTickIcon />,
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Video library",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: <CheckTickIcon />,
    content4: <CheckTickIcon />,
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Training",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: "5TB bandwidth/month",
    content4: "-",
    content5: <CheckTickIcon />,
  },
];

export const TableCardPropsDataForFourthBtn = [
  {
    rowStartHeadValue: "Seats",
    icon: <TableinsuffIcon />,
    content1: "4 Seat",
    content2: "1 Seat",
    content3: "4 Seat",
    content4: "1 Seat",
    content5: "Seat",
  },
  {
    rowStartHeadValue: "Video creation and uploading",
    icon: <TableinsuffIcon />,
    content1: "2 videos / month",
    content2: "800 videos / seat / year",
    content3: "1300 videos / seat / year",
    content4: "2800 videos / seat / year",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Videos stored in account",
    icon: <TableinsuffIcon />,
    content1: "50 videos",
    content2: "75 videos",
    content3: "120 videos",
    content4: "Unlimited",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Virtual Events",
    icon: <TableinsuffIcon />,
    content1: " 120 videos ",
    content2: " - ",
    content3: " 120 videos ",
    content4: " -",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Screen recording",
    icon: <TableinsuffIcon />,
    content1: "25 videos",
    content2: "Unlimited",
    content3: " - ",
    content4: "Unlimited",
    content5: "120 videos",
  },
  {
    rowStartHeadValue: "Bandwidth",
    icon: <TableinsuffIcon />,
    content1: "2TB bandwidth/month",
    content2: "9TB bandwidth/month",
    content3: "4TB bandwidth/month",
    content4: "5TB bandwidth/month",
    content5: "Custom",
  },
  {
    rowStartHeadValue: "Interactive video",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "6TB bandwidth/month",
    content3: "-",
    content4: "12TB bandwidth/month",
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Webinar API",
    icon: <TableinsuffIcon />,
    content1: " 120 videos ",
    content2: "-",
    content3: "Unlimited",
    content4: "-",
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Version history",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: <CheckTickIcon />,
    content4: <CheckTickIcon />,
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Video library",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: " -",
    content4: <CheckTickIcon />,
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Training",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: " <CheckTickIcon /> ",
    content3: "5TB bandwidth/month",
    content4: "-",
    content5: <CheckTickIcon />,
  },
];

export const TableCardPropsDataForFifthBtn = [
  {
    rowStartHeadValue: "Seats",
    icon: <TableinsuffIcon />,
    content1: "3 Seat",
    content2: "1 Seat",
    content3: "3 Seat",
    content4: "1 Seat",
    content5: "Seat",
  },
  {
    rowStartHeadValue: "Video creation and uploading",
    icon: <TableinsuffIcon />,
    content1: "2 videos / month",
    content2: "500 videos / seat / year",
    content3: "1000 videos / seat / year",
    content4: "2500 videos / seat / year",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Videos stored in account",
    icon: <TableinsuffIcon />,
    content1: "25 videos",
    content2: "85 videos",
    content3: "100 videos",
    content4: "Unlimited",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Virtual Events",
    icon: <TableinsuffIcon />,
    content1: " Unlimited ",
    content2: " - ",
    content3: " - ",
    content4: " -",
    content5: "Unlimited",
  },
  {
    rowStartHeadValue: "Screen recording",
    icon: <TableinsuffIcon />,
    content1: "25 videos",
    content2: "Unlimited",
    content3: "Unlimited",
    content4: "Unlimited",
    content5: "120 videos",
  },
  {
    rowStartHeadValue: "Bandwidth",
    icon: <TableinsuffIcon />,
    content1: "2TB bandwidth/month",
    content2: "7TB bandwidth/month",
    content3: "4TB bandwidth/month",
    content4: "5TB bandwidth/month",
    content5: "Custom",
  },
  {
    rowStartHeadValue: "Interactive video",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "6TB bandwidth/month",
    content3: "-",
    content4: "6TB bandwidth/month",
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Webinar API",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: "Unlimited",
    content4: "-",
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Version history",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: <CheckTickIcon />,
    content4: <CheckTickIcon />,
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Video library",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: <CheckTickIcon />,
    content4: <CheckTickIcon />,
    content5: <CheckTickIcon />,
  },
  {
    rowStartHeadValue: "Training",
    icon: <TableinsuffIcon />,
    content1: " - ",
    content2: "-",
    content3: "5TB bandwidth/month",
    content4: "-",
    content5: <CheckTickIcon />,
  },
];
